services:
  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ai" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  buyer-app:
    build: .
    container_name: buyer-app
    depends_on:
      pgvector-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pgvolume:
